folder: "./textures"

actions:
  imagemagick:
    enabled: False
    binary: "magick"
    arguments: "+noise Gaussian -attenuate 0.5 -resize 400%"
  sox:
    enabled: False
    binary: "sox"
    arguments: "-v 1000"
  optimize:
    enabled: True
    binary: "oxipng"
    arguments: "--opt 6 --strip all --alpha"
  optimizeogg:
    enabled: False
    binary: "~/Downloads/optivorbis"